# Generated by Django 4.1.5 on 2023-02-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(upload_to='CustomUser', verbose_name='аватарка'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='номер телефона'),
        ),
    ]
