# Generated by Django 4.1.5 on 2023-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_alter_usercustom_avatar_alter_usercustom_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='username',
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(upload_to='CustomUser/', verbose_name='аватарка'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
